//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1430757_CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        public int ID { get; set; }
        public string cust_ID { get; set; }
        public int LP_ID { get; set; }
        public int LP_price { get; set; }
        public Nullable<System.DateTime> LP_date { get; set; }
        public bool in_Cart { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
