//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1430757_CO5027
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int ID { get; set; }
        public string GU_ID { get; set; }
        public string LP_FName { get; set; }
        public string LP_LName { get; set; }
        public string LP_address { get; set; }
        public int LP_PCode { get; set; }
    }
}
